/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    crystals: Crystal;
    measurements: Measurement;
    processings: Processing;
    refinements: Refinement;
    publications: Publication;
    'chamber-types': ChamberType;
    search: Search;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    crystals: CrystalsSelect<false> | CrystalsSelect<true>;
    measurements: MeasurementsSelect<false> | MeasurementsSelect<true>;
    processings: ProcessingsSelect<false> | ProcessingsSelect<true>;
    refinements: RefinementsSelect<false> | RefinementsSelect<true>;
    publications: PublicationsSelect<false> | PublicationsSelect<true>;
    'chamber-types': ChamberTypesSelect<false> | ChamberTypesSelect<true>;
    search: SearchSelect<false> | SearchSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  admin: boolean;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "crystals".
 */
export interface Crystal {
  source: string;
  id: string;
  dimesions: {
    max: number;
    mid: number;
    min: number;
  };
  color: {
    a?: ('clear' | 'dull' | 'metallic' | 'opalescent') | null;
    b?:
      | (
          | 'light'
          | 'dark'
          | 'whitish'
          | 'blackish'
          | 'greyish'
          | 'brownish'
          | 'yellowish'
          | 'reddish'
          | 'blueish'
          | 'greenish'
          | 'pinkish'
          | 'orangeish'
        )
      | null;
    c:
      | 'colorless'
      | 'black'
      | 'white'
      | 'grey'
      | 'brown'
      | 'yellow'
      | 'red'
      | 'blue'
      | 'green'
      | 'pink'
      | 'violet'
      | 'orange';
  };
  shape:
    | 'block'
    | 'plate'
    | 'needle'
    | 'prism'
    | 'plank'
    | 'irregular'
    | 'cube'
    | 'trapezoid'
    | 'hexagonal'
    | 'octahedral'
    | 'rhobohedral'
    | 'spherical';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "measurements".
 */
export interface Measurement {
  id: number;
  crystal: string | Crystal;
  pi_name: string;
  grant_id: string;
  operator_name: string;
  facility_name: string;
  measurement_starting_date: string;
  experiment_type: 'single crystal' | 'powder' | 'non-ambient';
  _diffrn_ambient_temperature?: {
    measurement?: number | null;
    uncertainty?: number | null;
  };
  _diffrn_radiation_probe?: string | null;
  _diffrn_radiation_wavelength?: number | null;
  _diffrn_measurement_device_type?: string | null;
  _diffrn_detector_type?: string | null;
  _diffrn_reflns_theta_max?: number | null;
  resolution?: number | null;
  pressure?: number | null;
  pressure_measurement_location?: string | null;
  chamber_type?: (number | null) | ChamberType;
  opening_angle?: ('30' | '40' | '50') | null;
  pressure_medium?: string | null;
  comment?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "chamber-types".
 */
export interface ChamberType {
  id: number;
  name: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "processings".
 */
export interface Processing {
  id: number;
  author: string;
  measurement: number | Measurement;
  _diffrn_reflns_av_R_equivalents?: number | null;
  _diffrn_reflns_av_sigmaI_netI?: number | null;
  _diffrn_reflns_theta_min?: number | null;
  _diffrn_reflns_theta_max?: number | null;
  comment?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "refinements".
 */
export interface Refinement {
  id: number;
  author: string;
  next_refinements?:
    | {
        refinement: number | Refinement;
        id?: string | null;
      }[]
    | null;
  disorder: boolean;
  solvent_masking: boolean;
  aspherical_atom_model: 'IAM' | 'TAAM' | 'HAR';
  _chemical_formula_sum?: string | null;
  '_space_group_name_H-M_alt'?: string | null;
  _cell_length_a?: {
    measurement?: number | null;
    uncertainty?: number | null;
  };
  _cell_length_b?: {
    measurement?: number | null;
    uncertainty?: number | null;
  };
  _cell_length_c?: {
    measurement?: number | null;
    uncertainty?: number | null;
  };
  _cell_angle_alpha?: {
    measurement?: number | null;
    uncertainty?: number | null;
  };
  _cell_angle_beta?: {
    measurement?: number | null;
    uncertainty?: number | null;
  };
  _cell_angle_gamma?: {
    measurement?: number | null;
    uncertainty?: number | null;
  };
  _cell_volume?: {
    measurement?: number | null;
    uncertainty?: number | null;
  };
  _diffrn_reflns_av_R_equivalents?: number | null;
  _diffrn_reflns_Laue_measured_fraction_full?: number | null;
  _refine_ls_R_factor_gt?: number | null;
  _refine_ls_wR_factor_ref?: number | null;
  comment?: string | null;
  final?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "publications".
 */
export interface Publication {
  id: number;
  doi: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This is a collection of automatically created search results. These results are used by the global site search and will be updated automatically as documents in the CMS are created or updated.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "search".
 */
export interface Search {
  id: number;
  title?: string | null;
  priority?: number | null;
  doc:
    | {
        relationTo: 'crystals';
        value: string | Crystal;
      }
    | {
        relationTo: 'measurements';
        value: number | Measurement;
      }
    | {
        relationTo: 'processings';
        value: number | Processing;
      }
    | {
        relationTo: 'refinements';
        value: number | Refinement;
      }
    | {
        relationTo: 'publications';
        value: number | Publication;
      };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'crystals';
        value: string | Crystal;
      } | null)
    | ({
        relationTo: 'measurements';
        value: number | Measurement;
      } | null)
    | ({
        relationTo: 'processings';
        value: number | Processing;
      } | null)
    | ({
        relationTo: 'refinements';
        value: number | Refinement;
      } | null)
    | ({
        relationTo: 'publications';
        value: number | Publication;
      } | null)
    | ({
        relationTo: 'chamber-types';
        value: number | ChamberType;
      } | null)
    | ({
        relationTo: 'search';
        value: number | Search;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  admin?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "crystals_select".
 */
export interface CrystalsSelect<T extends boolean = true> {
  source?: T;
  id?: T;
  dimesions?:
    | T
    | {
        max?: T;
        mid?: T;
        min?: T;
      };
  color?:
    | T
    | {
        a?: T;
        b?: T;
        c?: T;
      };
  shape?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "measurements_select".
 */
export interface MeasurementsSelect<T extends boolean = true> {
  crystal?: T;
  pi_name?: T;
  grant_id?: T;
  operator_name?: T;
  facility_name?: T;
  measurement_starting_date?: T;
  experiment_type?: T;
  _diffrn_ambient_temperature?:
    | T
    | {
        measurement?: T;
        uncertainty?: T;
      };
  _diffrn_radiation_probe?: T;
  _diffrn_radiation_wavelength?: T;
  _diffrn_measurement_device_type?: T;
  _diffrn_detector_type?: T;
  _diffrn_reflns_theta_max?: T;
  resolution?: T;
  pressure?: T;
  pressure_measurement_location?: T;
  chamber_type?: T;
  opening_angle?: T;
  pressure_medium?: T;
  comment?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "processings_select".
 */
export interface ProcessingsSelect<T extends boolean = true> {
  author?: T;
  measurement?: T;
  _diffrn_reflns_av_R_equivalents?: T;
  _diffrn_reflns_av_sigmaI_netI?: T;
  _diffrn_reflns_theta_min?: T;
  _diffrn_reflns_theta_max?: T;
  comment?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "refinements_select".
 */
export interface RefinementsSelect<T extends boolean = true> {
  author?: T;
  next_refinements?:
    | T
    | {
        refinement?: T;
        id?: T;
      };
  disorder?: T;
  solvent_masking?: T;
  aspherical_atom_model?: T;
  _chemical_formula_sum?: T;
  '_space_group_name_H-M_alt'?: T;
  _cell_length_a?:
    | T
    | {
        measurement?: T;
        uncertainty?: T;
      };
  _cell_length_b?:
    | T
    | {
        measurement?: T;
        uncertainty?: T;
      };
  _cell_length_c?:
    | T
    | {
        measurement?: T;
        uncertainty?: T;
      };
  _cell_angle_alpha?:
    | T
    | {
        measurement?: T;
        uncertainty?: T;
      };
  _cell_angle_beta?:
    | T
    | {
        measurement?: T;
        uncertainty?: T;
      };
  _cell_angle_gamma?:
    | T
    | {
        measurement?: T;
        uncertainty?: T;
      };
  _cell_volume?:
    | T
    | {
        measurement?: T;
        uncertainty?: T;
      };
  _diffrn_reflns_av_R_equivalents?: T;
  _diffrn_reflns_Laue_measured_fraction_full?: T;
  _refine_ls_R_factor_gt?: T;
  _refine_ls_wR_factor_ref?: T;
  comment?: T;
  final?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "publications_select".
 */
export interface PublicationsSelect<T extends boolean = true> {
  doi?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "chamber-types_select".
 */
export interface ChamberTypesSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "search_select".
 */
export interface SearchSelect<T extends boolean = true> {
  title?: T;
  priority?: T;
  doc?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}